# Game Theory
Game theory considers situations where so-called players (e.g., people, firms, political parties) make decisions as strategic reactions to other players' actions. Examples are reality TV shows with people competing against each other, political parties choosing their position on an issue or during an election, or pricing strategies of firms in an oligopolistic environment. In addition, almost every sport as well as war is based on game theory. The final scene of the 1983 movie [WarGames](https://www.imdb.com/title/tt0086567/) is an excellent example of game theory.

In economics and business, one of the most general problems is outguessing a rival. Strategic interaction  means that a player's payoff depends on other players' actions. A player's optimal action depends on the expectations of what other players will do. Strategic interactions among players is considered in a non-cooperative setting, i.e., binding agreements among players do not exist. For example, there is no cooperation in the game of two sport teams. Cooperation may or may not occur among players as a result of rational decisions, e.g., trigger strategies. Full information, i.e., players are aware of the payoff structure of games, is assumed for this chapter.

Economic models based on game theory allow drawing conclusions that can be used to understand real world strategic interactions. Every game has three components: 

1. Players: Finite number of players (at least 2)
2. Actions: Set of actions for each player
3. Payoffs: Those can be ranked at least ordinally

Payoffs may be in form of a change in (marginal) utility, revenue, profit, or some non-monetary change in satisfaction. A player's strategy is the complete contingent plan. If it could be written down, any other agent could follow the plan and duplicate player's actions. Thus, a strategy is a player's course of action involving a set of actions (moves) dependent on actions of other players. A unique equilibrium or a set of equilibria may occur within a set of strategies is called a Nash equilibrium (after mathematician John Nash). Not all games have a Nash equilibrium and some games may have a number of Nash equilibria. In the movie A Beautiful Movie, John Nash's discovery is [portrayed to have happened in a bar](https://www.youtube.com/watch?v=CemLiSI5ox8):

> If we all go for the blonde and block each other, not a single one of us is going to get her. So then we go for her friends, but they will all give us the cold shoulder because no one likes to be second choice. But what if none of us goes for the blonde? We won't get in each other's way and we won't insult the other girls. It's the only way to win.

Note that the movie is wrong about the Nash Equilibrium. The situation described is not a Nash Equilibrium.

## Single Shot Games
We now present several classical simultaneous move games that you can find in almost every economics textbook and illustrate different concepts associated with game theory.

### Prisoner's Dilemma
The best-known game is the Prisoner's Dilemma. The payoff table for the two players is represented as:

|              |         | Player B        ||
|:-------------|:--------|:-------:|:------:|
|              |         | Confess | Deny   |
| **Player A** | Deny    |    1,1  | 20,0   |
|              | Confess |   0,20  | 5,5    |

In the prisoner's dilemma game, there is one Nash Equilibrium. Note that it is not the optimal outcome. Every Nash Equilibrium is characterized as a state where no player has the incentive to deviate. A more thorough video explaining the prisoner's dilemma can be found [here](https://www.youtube.com/watch?v=t9Lo2fgxWHw). 

For a more real world application of a simultaneous move game consider a penalty shot-out in soccer. There are two players (one of them is the goal keeper) and assume (for simplicity) that they have two actions: left or right. That is, the player kicking the ball has to decide whether to kick the ball in the left or right corner and the goalkeeper has to decide whether to jump left or right. Note that the soccer ball travels to fast and the goal keeper cannot observe the direction of the ball. How this looks is demonstrated in this sequence of a [penalty shootout between Argentina and the Netherlands](https://youtu.be/p9QuQBrPTE8?t=276). 

### Stag Hunt
Consider the following game:

|              |         | Player B        ||
|:-------------|:--------|:-------:|:------:|
|              |         | Stag    | Hare   |
| **Player A** | Stag    |    2,2  | 0,1    |
|              | Hare    |   1,0   | 1,1    |

### Up or Down
A dominant strategy is a strategy that is preferred to another no matter what other players do. When all players have a dominant strategy, an equilibrium of dominant strategies exists that is determined without a player having to consider behavior of other players. Consider the following game:

|              |         | Player B        ||
|:-------------|:--------|:-------:|:------:|
|              |         | up      | down   |
| **Player A** | up      |  10,10  | 7,7    |
|              | down    |   7,7   | 5,5    |

### Rock, Paper, Scissors
It is also possible to have a game with no Nash Equilibrium. Rock, Paper, Scissors is an example for such a game:

|              |   | Player B                 |||
|:-------------|:--|:---:|:------:|:-------:|
|              |   | R   | P      | S       
| **Player A** | R | d,d | l,w    | w,l    
|              | P | w,l | d,d    | l,w    
|              | S | l,w | w,l    | d,d    

If there is no Nash Equilibrium with a pure strategy, we can resort to a mixed strategy. If you think about how you play rock, paper, scissors, you can imagine what a mixed strategy does: randomize your actions. 

### Cartel Game
Let us now turn to games that are more specific to economics. Consider a cartel with two firms. Both firms have to decide whether to cheat or comply with the cartel agreement:

|              |             | Player B            ||
|:-------------|:------------|:-----------:|:------:|
|              |             | Don't cheat | Cheat  |
| **Player A** | Don't cheat | 50,50       | 45,54  |
|              | Cheat       | 54,45       | 48,48  |

### Beach location game
Games do not necessarily need to be displayed in a payoff matrix. Consider a game where beach-goers are uniformly distributed on a stretch of beach that goes from *A* to *B* . You have two ice cream vendors located at *A* and *B* initially. Customers go to the nearest vendor. In this initial situation, each vendor gets 50\% of the market. Is this initial situation a Nash Equilibrium?  

## Repeated Games
We have seen that in the single shot prisoner's dilemma there is no Nash Equilibrium. It is possible to identify an optimal strategy for an infinitely repeated game. This is called a trigger strategy. In the first round, player *A* cooperates and does not confess. In every round after, if player *B* cooperated on previous round, *A* cooperates. If *B* defected on previous round, *A* then defects. Strategy does very well because it offers an immediate punishment for defection and has a forgiving strategy. An application is the carrot-and-stick strategy that underlies most attempts at raising children. Consider the following game between Pepsi and Coca-Cola. Note that one-time win from a low price is 5 and the loss in repeated games is 4 (discount rate becomes important).

|              |             | Player B            ||
|:-------------|:------------|:-----------:|:------:|
|              |             | Don't cheat | Cheat  |
| **Player A** | Don't cheat | 12,12       | 6,17   |
|              | Cheat       | 17,6        | 8,8    |

## Sequential Games and Entry Deterrence
There is a YouTube video associated with this section explaining the concepts presented:

- [Sequential Games and Entry Deterrence](https://youtu.be/D1Ij0o1FEYI)

In a sequential game, one player knows the other player's choice before taking an action (perfect information). For example, a firm determines consumer demand before making a pricing decision or a politician knows the opponent's stance on an issue before making their own. So-called backward induction determines a sub-game perfect Nash equilibrium by working backward toward the root in a game tree. Once the game is understood through backward induction, players play it forward. To apply backward induction, first determine the optimal actions at last decision nodes. Then determine optimal actions at next-to-last decision nodes, assuming that optimal actions will follow at next decision nodes. Backward induction implicitly assumes that a player's strategy will consist of optimal actions at every node in game tree.

Sequential games can be used for entry deterrence. Firms or governments who act first have an advantage which leads to a preemption games. Strategic pre-commitments can affect future payoffs. For example, a firm adopting a large production capacity in a new market can saturate the market and make it difficult for other firms to enter.

## Exercises
Note that in all the questions, the term Nash Equilibrium is used but it also refers to the plural, i.e., Nash Equilibria.

1. ***Apple Juice Companies*** (**): Two competing companies in the apple juice industry simultaneously decide on their weekly pricing strategy. The actions available to each firm are price low or price high. The payoffs associated with this situation is depicted in the payoff matrix below. In a single shot game, what is the Nash Equilibrium. In a repeated game, describe a trigger strategy and the resulting Nash Equilibrium.

    |              |             | Player B              ||
    |:-------------|:------------|:---------:|:----------:|
    |              |             | Price low | Price high |
    | **Player A** | Price low   | 30, 30    | 60, 20     |
    |              | Price high  | 20, 60    | 50, 50     |


2. ***Emergency Call*** (**): Perhaps you have been in this situation before. You (and many others) witness an accident or a crime and you have to decided whether to call 911 yourself or rely on other witnesses to do so. The problem is that you usually do not know whether an emergency call was made or not. Suppose an event is witnessed by two people and the cost of making an emergency call is $c>0$. Both people get a benefit of $x$ from the event being reported to first responders and $x>c$. A payoff of zero is received if the event goes unreported. Draw the payoff matrix and determine the Nash Equilibrium. This is a simultaneous move game. What is the Nash equilibrium if there are more than two people?
        
3. ***Being on Time*** (**): A friend of mine (actually, more than just one) regularly arrives late. It annoys them when they have to come on time. If I know that they come late on a regular basis, should I adjust my timing as well? Consider the following payoff matrix and find the Nash Equilibrium:

    |        |         | My friend             ||
    |:-------|:--------|:---------:|:----------:|
    |        |         | On time   | Late       |
    | **Me** | On time | 100, 80   | 10, 90     |
    |        | Late    | 80, 80    | 90, 90     |

4. ***Public Goods Game*** (**): There is a public goods game in experimental economics. Each player initially has \$20 and then secretly selects whether to contribute the amount to a public pool or not. If the player does not contribute, they simply get the \$20. If the money is contributed, the amount in the public pool is multiplied by 1.5 and divided equally by the number of players and returned. The game represents a situation where the contribution to a public good (e.g., education or infrastructure) increases the payoff for everyone in society. For example, if both players contribute, they get back $(\$40 \cdot 1.5)/2=\$30$. Draw the payoff matrix and identify the Nash Equilibrium strategies

5. ***Holiday Gifts*** (**): My parents do not want to exchange gifts during the holiday season because it increases stress during an already busy period. Of course, my parents and I have the possibility to purchase gifts anyway and deviate from the arrangements of not purchasing gifts. So each party has two possible actions: (1) buy gifts and (2) no gifts. The utility of the parties is depicted in the matrix below. Of course, the most catastrophic outcome is when your parents purchased a gift and I sit there empty-handed. The payoff for that situation below reflects that shame (me) and disappointment (parents). What is the Nash Equilibrium? What is the problem with that Nash Equilibrium?

    |              |             | Parents                ||
    |:-------------|:------------|:-----------:|:---------:|
    |              |             | Buy gifts   | No gifts  |
    | **Me**       | Buy gifts   | 100,100     | 50,10     |
    |              | No gifts    | 0,0         | 95,95     |
    
6. ***Collaborative Work*** (***): You and another student are engaged in a group project for a class. Each of you can exert three levels of effort: Low, medium, and high. Let us assign the numeric values of 1, 2, and 3 to low, medium, and high effort, respectively. The score you receive (together) on the project depends on the sum of effort you each put in. Let the total work be $w$ then the score $s$ you receive is given by $s=18+46 \cdot \ln(w)$ where $\ln$ represents the natural log. Round to the nearest integer for the subsequent calculations. We can do a simple example to illustrate how the equation works. Suppose that both of you put in the lowest effort. In that case, $w=2$ and $s=18+46 \cdot \ln(2)=49.88$. Rounded to the nearest integer, you receive a score of 50 for the homework. Your payoff ($\pi$) is determined by the grade minus the effort you put in: $\pi = grade - 10 \cdot w$. So your payoff given the example would be 30.  
     a. Suppose you independently have to decide how much effort to put in the project. You do not observe the effort of the other person prior to receiving the grade. What is the Nash Equilibrium?
     b. Suppose that one of you works on the project first and then submits the part to the other person. That person can see the effort that was exerted and decides how much effort to put in. What is Nash Equilbrium in this sequential game?